const MenuItems = [
    {
        id: 1,
        itemId: "bed01",
        name: "Bed",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17396.png",
    },
    {
        id: 2,
        itemId: "sofa01",
        name: "Sofa",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6958.png",
    },
    {
        id: 3,
        itemId: "armchair01",
        name: "Armchair",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7023.png",
    },
    {
        id: 4,
        itemId: "cupboard01",
        name: "Cupboard",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16716.png",
    },
    {
        id: 5,
        itemId: "dresser01",
        name: "Dresser",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG177.png",
    },
];

const Items = [
    {
        id: 1,
        itemId: "bed01",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17424.png",
        name: "Modern Bed",
        ratings: 5,
        price: "7.5",
    },
    {
        id: 2,
        itemId: "bed01",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17410.png",
        name: "Black Bed",
        ratings: 5,
        price: "12",
    },
    {
        id: 3,
        itemId: "bed01",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17408.png",
        name: "Modern Bed 1",
        ratings: 5,
        price: "12",
    },
    {
        id: 4,
        itemId: "bed01",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17404.png",
        name: "Modern Bed 2",
        ratings: 5,
        price: "12",
    },
    {
        id: 5,
        itemId: "bed01",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17391.png",
        name: "Gold Bed",
        ratings: 5,
        price: "12",
    },
    {
        id: 6,
        itemId: "bed01",
        imgSrc: "https://pngimg.com/uploads/bed/bed_PNG17376.png",
        name: "White Bed",
        ratings: 5,
        price: "12",
    },
    {
        id: 7,
        itemId: "sofa01",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6966.png",
        name: "Black Modern Sofa",
        ratings: 5,
        price: "12",
    },
    {
        id: 8,
        itemId: "sofa01",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6964.png",
        name: "Green Sofa",
        ratings: 5,
        price: "12",
    },
    {
        id: 9,
        itemId: "sofa01",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6956.png",
        name: "Modern Black Sofa",
        ratings: 5,
        price: "12",
    },
    {
        id: 10,
        itemId: "sofa01",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6946.png",
        name: "Grey Sofa",
        ratings: 4,
        price: "12",
    },
    {
        id: 11,
        itemId: "sofa01",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6938.png",
        name: "White Sofa",
        ratings: 4,
        price: "12",
    },
    {
        id: 12,
        itemId: "sofa01",
        imgSrc: "https://pngimg.com/uploads/sofa/sofa_PNG6923.png",
        name: "Gray Sofa",
        ratings: 4,
        price: "12",
    },
    {
        id: 13,
        itemId: "armchair01",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7069.png",
        name: "Green Armchair",
        ratings: 4,
        price: "12",
    },
    {
        id: 14,
        itemId: "armchair01",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7041.png",
        name: "Black Armchair",
        ratings: 4,
        price: "12",
    },
    {
        id: 15,
        itemId: "armchair01",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7034.png",
        name: "Brown Armchair",
        ratings: 4,
        price: "12",
    },
    {
        id: 16,
        itemId: "armchair01",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7023.png",
        name: "Gray Armchair",
        ratings: 4,
        price: "12",
    },
    {
        id: 17,
        itemId: "armchair01",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7071.png",
        name: "White Armchair",
        ratings: 4,
        price: "12",
    },
    {
        id: 18,
        itemId: "armchair01",
        imgSrc: "https://pngimg.com/uploads/armchair/armchair_PNG7067.png",
        name: "Vintage Armchair",
        ratings: 3,
        price: "12",
    },
    {
        id: 19,
        itemId: "cupboard01",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16763.png",
        name: "Vintage Cupboard",
        ratings: 3,
        price: "7.5",
    },
    {
        id: 20,
        itemId: "cupboard01",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16716.png",
        name: "Modern Cupboard",
        ratings: 3,
        price: "7.5",
    },
    {
        id: 21,
        itemId: "cupboard01",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16710.png",
        name: "White Cupboard",
        ratings: 3,
        price: "7.5",
    },
    {
        id: 22,
        itemId: "cupboard01",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16750.png",
        name: "Vintage Cupboard",
        ratings: 3,
        price: "9",
    },
    {
        id: 23,
        itemId: "cupboard01",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16756.png",
        name: "Modern Cupboard",
        ratings: 3,
        price: "9",
    },
    {
        id: 24,
        itemId: "cupboard01",
        imgSrc: "https://pngimg.com/uploads/cupboard_closet/cupboard_closet_PNG16763.png",
        name: "Vintage Cupboard",
        ratings: 3,
        price: "9",
    },
    {
        id: 25,
        itemId: "dresser01",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG183.png",
        name: "Modern Dresser",
        ratings: 4,
        price: "9",
    },
    {
        id: 26,
        itemId: "dresser01",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG176.png",
        name: "Vintage Dresser",
        ratings: 4,
        price: "9",
    },
    {
        id: 27,
        itemId: "dresser01",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG172.png",
        name: "Vintage Dresser",
        ratings: 4,
        price: "9",
    },
    {
        id: 28,
        itemId: "dresser01",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG177.png",
        name: "Modern Gray Dresser",
        ratings: 4,
        price: "9",
    },
    {
        id: 29,
        itemId: "dresser01",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG137.png",
        name: "Vintage Dresser",
        ratings: 4,
        price: "9",
    },
    {
        id: 30,
        itemId: "dresser01",
        imgSrc: "https://pngimg.com/uploads/dresser/dresser_PNG98.png",
        name: "Modern Dresser",
        ratings: 4,
        price: "9",
    }
]

export { MenuItems, Items }